### ISSUE TITLE
[Android] File picker type image returns null

### ISSUE THREAD

**Issue by OlehMarchenko95** [miguelpruivo/flutter_file_picker#1025]
**Describe the bug**
Unable to retrieve an image if trying to pick files with type **image**.
Also theres an issue on stackoverflow [File picker type image returns null flutter](https://stackoverflow.com/questions/71704916/file-picker-type-image-returns-null-flutter)

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 10 and higher (lower version were not checked)

**OS Vendors**

- Samsung
- Xiaomi

**How are you picking?**
```dart
FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image);
if (result != null) {
  PlatformFile file = result.files.first;
  print(file.name);
  print(file.bytes);
  print(file.size);
  print(file.extension);
  print(file.path);
} else {
  print("null);
}
```

**Environment**
Latest stable flutter 2.10.4

**Comment by miguelpruivo** [comment]
Does this happen only with those vendors? Could you try with the emulator?

**Comment by OlehMarchenko95** [comment]
I've encountered this issue only with those vendors. Emulators work correctly, it seems like the issue is specific to at least those 2 vendors

**Comment by xkxeeshankhan** [comment]
> Running into the same problem on one of the testdevices.
> 
> **Problem** The filepicker returns null on one of the testdevices. It returns the correct FilePickerResult on the other test devices and the emulator. **Pick** final FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image, withData: false);
> 
> _Specifications of the device that returns null:_ **Platform+Version** Android 12 **Device:** Galaxy S21 5G

Same result happening for
**Device**
Huawei P30 Pro
**Android 10**

**Comment by DonWasyl** [comment]
same problem :/
Android 12

**Comment by mdeandrea-mrmilu** [comment]
Try set param `withData` to true

**Comment by OlehMarchenko95** [comment]
This issue is still reproducible

**Comment by mdeandrea-mrmilu** [comment]
> Try set param `withData` to true

Yes, but with this is solved @OlehMarchenko95

**Comment by OlehMarchenko95** [comment]
@mdeandrea-mrmilu nope, plugin doesn't work as expected even with this flag

in the paltform logs there's `User cancelled the picker request`

**Comment by rafalbednarczuk** [comment]
I can confirm it's still a bug on some devices, in my case xiaomi devices.   
For images only I use https://pub.dev/packages/image_picker instead.

For all files, flutter_file_picker works fine

**Comment by ZahidMahmood-Android** [comment]
Hi guys, the solution that worked for me is try to set launch mode = Standard in Main Activity in AndroidManifest file

**Comment by roberto-gigli** [comment]
This still happening in 2025

Device:
Samsung Galaxy A21s Android 12
