### ISSUE TITLE
iOS 16.0 dev 1 beta - compile failure

### ISSUE THREAD

**Issue by imprecis** [miguelpruivo/flutter_file_picker#1047]
File picker version 4.6.1
MacOS Ventura dev 1 beta
Flutter 3.0.1

The issue seems to be with DKImagePickerController

```    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    Result bundle written to path:
        /var/folders/v3/6j3tgx_s6r3g562nyw_rphnc0000gn/T/flutter_tools.7vxNcY/flutter_ios_build_temp_dirSRkh23/temporary_xcresult_bundle
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/Users/test/Documents/GitHub/test/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:67:5

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro.```

**Comment by yahu1031** [comment]
Here are few more logs

```
Launching lib/main.dart on iPhone 12 in debug mode...
Xcode build done.                                           40.1s
Failed to build iOS app
Error output from Xcode build:
â†³
    2022-06-17 19:55:33.250 xcodebuild[12143:73785] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x600003a06610:'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk'>': SDK with name 'macosx13.0' being superseded by SDK with 'macosx13.0'.
    ** BUILD FAILED **
Xcode's output:
â†³
    Writing result bundle at path:
    	/var/folders/xz/3m35lfq959s2mhqp7nw6ky040000gn/T/flutter_tools.sJTjbA/flutter_ios_build_temp_dirNMZozl/temporary_xcresult_bundle
/Users/minnu/.pub-cache/hosted/pub.dartlang.org/flutter_phone_direct_caller-2.1.1/ios/Classes/FlutterPhoneDirectCallerPlugin.m:24:22: warning: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid. [-Wdeprecated-declarations]
        number = [number stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
                         ^
    In module 'UIKit' imported from /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/Target Support Files/flutter_phone_direct_caller/flutter_phone_direct_caller-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:601:1: note: 'stringByAddingPercentEscapesUsingEncoding:' has been explicitly marked deprecated here
    - (nullable NSString *)stringByAddingPercentEscapesUsingEncoding:(NSStringEncoding)enc API_DEPRECATED("Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.", macos(10.0,10.11), ios(2.0,9.0), watchos(2.0,2.0), tvos(9.0,9.0));
    ^
    1 warning generated.
/Users/minnu/.pub-cache/hosted/pub.dartlang.org/flutter_phone_direct_caller-2.1.1/ios/Classes/FlutterPhoneDirectCallerPlugin.m:24:22: warning: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid. [-Wdeprecated-declarations]
        number = [number stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
                         ^
    In module 'UIKit' imported from /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/Target Support Files/flutter_phone_direct_caller/flutter_phone_direct_caller-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:601:1: note: 'stringByAddingPercentEscapesUsingEncoding:' has been explicitly marked deprecated here
    - (nullable NSString *)stringByAddingPercentEscapesUsingEncoding:(NSStringEncoding)enc API_DEPRECATED("Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.", macos(10.0,10.11), ios(2.0,9.0), watchos(2.0,2.0), tvos(9.0,9.0));
    ^
    1 warning generated.
    error: the following command failed with exit code 0 but produced no further output
    SwiftEmitModule normal x86_64 Emitting\ module\ for\ DKPhotoGallery (in target 'DKPhotoGallery' from project 'Pods')
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:39:52: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDataSource: class {
                                                       ^~~~~
                                                       AnyObject
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:55:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:39:52: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDataSource: class {
                                                       ^~~~~
                                                       AnyObject
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:55:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/PlayerPreview/DKPlayerView.swift:242:38: warning: cannot access property 'player' with a non-sendable type 'AVPlayer' from non-isolated deinit; this is an error in Swift 6
            guard let currentItem = self.player.currentItem, currentItem.observationInfo != nil else { return }
                                         ^
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/PlayerPreview/DKPlayerView.swift:242:38: warning: cannot access property 'player' with a non-sendable type 'AVPlayer' from non-isolated deinit; this is an error in Swift 6
            guard let currentItem = self.player.currentItem, currentItem.observationInfo != nil else { return }
                                         ^
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:68:6: error: stored properties cannot be marked potentially unavailable with '@available'
        @available(iOS 13.0, *)
         ^
    Command SwiftCompile failed with a nonzero exit code
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 16.0.99. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
    /Users/minnu/Documents/Flutter/The @platform/apps/buzz/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 16.0.99. (in target 'TOCropViewController' from project 'Pods')
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    Result bundle written to path:
    	/var/folders/xz/3m35lfq959s2mhqp7nw6ky040000gn/T/flutter_tools.sJTjbA/flutter_ios_build_temp_dirNMZozl/temporary_xcresult_bundle
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/Users/minnu/Documents/Flutter/The%20@platform/apps/buzz/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:67:5

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
Could not build the application for the simulator.
Error launching application on iPhone 12.
Exited
```

```
MacOS Ventura 13.0 Beta (22A5266r)
iOS 16.0
Flutter v3.0.2
file_picker: ^4.6.1
```

**Comment by armandojimenez** [comment]
I have the same error, If I open xCode, it say: error build: Framework not found DKImagePickerController

**Comment by yahu1031** [comment]
@miguelpruivo Any idea about it?

**Comment by ahmednfwela** [comment]
I am having the same issue

**Comment by theniceboy** [comment]
Same issue here

**Comment by ossamaghayghay** [comment]
same issue here.any solution

**Comment by lulumeimei** [comment]
any update for this issue?

**Comment by SimonHausdorf** [comment]
It was fixed here already https://github.com/zhangao0086/DKImagePickerController/pull/700 but I think it is not published yet.

**Comment by JagandeepBrar** [comment]
@miguelpruivo a new version of DKImagePickerController has been published (4.3.4) that should resolve this problem.

**Comment by armandojimenez** [comment]
> @miguelpruivo a new version of DKImagePickerController has been published (4.3.4) that should resolve this problem.

Do we need to update any flutter package?

**Comment by armandojimenez** [comment]
Tried the 4.3.4 uodate, but I can't run that version on my phone. It says that the package does not have BITCODE enabled (need this for apple watch support), and also is asking me to select and sign DKImagePickerController with a development team

**Comment by Brazol** [comment]
Still happening on latest version (iOS 16 beta 6, Xcode 14 beta 5). Is there any fix for this?

**Comment by lifenautjoe** [comment]
Hey, this was not fixed. Why is this closed? :-( 

Now failing on the official iOS 16 release.

```
    /Users/joelhernandez/Documents/code/somus/somus-app/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:68:6: error: stored properties cannot be marked potentially unavailable with '@available'
        @available(iOS 13.0, *)
         ^
    note: Building targets in dependency order
```

**Comment by yahu1031** [comment]
tried `pod install`?

**Comment by lifenautjoe** [comment]
Jeeeeeesus...

`pod update` did it.

Thank you @yahu1031

**Comment by ArthurREGNARD** [comment]
On Xcode, go to your project > View > Navigators > Project and Select Pods.

For each targets, in Signing & Capabilities,  select your Team


OR Update to recommended settings

**Comment by anand-rsoft** [comment]
> On Xcode, go to your project > View > Navigators > Project and Select Pods.
> 
> For each targets, in Signing & Capabilities, select your Team
> 
> OR Update to recommended settings

🙏 Thanks , It works
