### ISSUE TITLE
Unable to pick files with `custom` or `any` file type on Android 14

### ISSUE THREAD

**Issue by VladStarikovEk** [miguelpruivo/flutter_file_picker#1404]
**Describe the bug**
When picking files with `custom` or `any` file type on Android 14, when one or multiple files are picked it just closes assuming that the user closed it. I also got `I/FilePickerDelegate(21624): User cancelled the picker request` message in logs.

When picking `image`, `audio`, `video` or `media` everything works fine, but the picker has a `gallery` UI, rather then `file explorer` UI. I also checked this on Android 13 emulator - it works file there.

**Platform**

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Pixel 5 - Android 14

**How are you picking?**
```
final pickerResult = await _filePicker.pickFiles(
      type: FileType.custom,
      allowMultiple: true,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
 );
```
or
```
final pickerResult = await _filePicker.pickFiles(
      type: FileType.any,
);
```

**Details to reproduce the issue**

**Error Log**
```
D/FilePickerDelegate(21624): Selected type */*
I/FilePickerDelegate(21624): User cancelled the picker request
```

**Screenshots and/or video**

https://github.com/miguelpruivo/flutter_file_picker/assets/99865323/ade3be44-b8f9-48b8-a509-d7aff62de0ad
<img width="932" alt="Screenshot 2023-11-08 at 15 35 34" src="https://github.com/miguelpruivo/flutter_file_picker/assets/99865323/0d2d2d0f-86ba-45d2-8e76-e77b5c8c4c47">

**Flutter Version details**
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale en-UA)
    • Flutter version 3.13.9 on channel stable at /Users/vstarikov/fvm/versions/3.13.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/vstarikov/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/vstarikov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 0B241FDD4001ZT • android-arm64  • Android 14 (API 34)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Additional context**
Requested permissions in `AndroidManifest`

```
   <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />
```

**Comment by DominicOrga** [comment]
I am also experiencing this issue, but in my case it occurs on my Pixel 4A Android 13.
What's weird is that the file picker does not work on my main (large) project, but works fine on a newly created test project.

**How are you picking?**
```
FilePicker.platform.pickFiles(
  allowMultiple: true,
  allowedExtensions: ['pdf'],
  type: FileType.custom,
);
```

**Output (Main Project):**
```
D/FilePickerUtils(26411): Allowed file extensions mimes: [application/pdf]
D/FilePickerDelegate(26411): Selected type */*
I/FilePickerDelegate(26411): User cancelled the picker request
```

**Output (Test Project):**
```
D/FilePickerUtils(28311): Allowed file extensions mimes: [application/pdf]
D/FilePickerDelegate(28311): Selected type */*
I/FilePickerUtils(28311): Caching from URI: content://com.android.providers.media.documents/document/document%3A83
D/FilePickerUtils(28311): File loaded and cached at:/data/user/0/com.example.file_picker_test/cache/file_picker/dummy.pdf
D/FilePickerDelegate(28311): File path:[com.mr.flutter.plugin.filepicker.FileInfo@144d1d0]
```

**Comment by fesaworld** [comment]
i got the same problem, and i found a way to solve it..

you can try changing android:launchMode="singleInstance" in /main/AndroidManifest.xml to android:launchMode="singleTop"

![image](https://github.com/miguelpruivo/flutter_file_picker/assets/57564538/3d3ddf06-b421-4b98-9176-23a8347e32e3)

**Comment by VladStarikovEk** [comment]
@TheCarpetMerchant Sadly - no. We still experiencing it.

**Comment by TheCarpetMerchant** [comment]
@VladStarikovEk there's a pull request opened for the fix. Just got it into prod and users confirm it works.
The pull request is 35 commits behind, so I made my own fork for it.

**Comment by VladStarikovEk** [comment]
> @VladStarikovEk there's a pull request opened for the fix. Just got it into prod and users confirm it works. The pull request is 35 commits behind, so I made my own fork for it.

Will try it. Thanks!

**Comment by VladStarikovEk** [comment]
I'm glad to report that the fix from [this](https://github.com/miguelpruivo/flutter_file_picker/pull/1380) PR works.
For now I'm using this way to add `file_picker` dependency:
```YAML
  file_picker:
    git:
      url: https://github.com/melWiss/flutter_file_picker.git
```

**Comment by zambetpentru** [comment]
> I'm glad to report that the fix from [this](https://github.com/miguelpruivo/flutter_file_picker/pull/1380) PR works. For now I'm using this way to add `file_picker` dependency:
> 
> ```yaml
>   file_picker:
>     git:
>       url: https://github.com/melWiss/flutter_file_picker.git
> ```

I confirm it's also working on my Samsung Galaxy when upgraded to Android 14

**Comment by TheCarpetMerchant** [comment]
Up

**Comment by kiokumicu** [comment]
Up

**Comment by arthurgiani** [comment]
up

**Comment by maharramg** [comment]
Up

**Comment by ambr89** [comment]
up

**Comment by mauriciotogneri** [comment]
up

**Comment by zambetpentru** [comment]
up

**Comment by devkeycloud** [comment]
Pixel 7а, android 14 - same problem

**Comment by bypass112** [comment]
Galaxy S22 Ultra, Android 14 - same problem

**Comment by DarenF-20C** [comment]
up

**Comment by erfan-git** [comment]
up

**Comment by Cloud3886** [comment]
up

**Comment by TheCarpetMerchant** [comment]
Up

**Comment by zambetpentru** [comment]
Bounce

**Comment by zambetpentru** [comment]
Bounce, bad bot

**Comment by miguelpruivo** [comment]
What is the solution purposed for this? Not sure what about the consequences of limiting it for single. I recall that it could introduce some issues but don't remember which.

**Comment by zambetpentru** [comment]
Bad bot

**Comment by TheManuz** [comment]
Bad bot

**Comment by zambetpentru** [comment]
Bad bot

**Comment by zambetpentru** [comment]
Bad bot

**Comment by TheManuz** [comment]
Yeah, we know it. Bad bot

**Comment by Shreyas-Mith** [comment]
any updates?

**Comment by TheManuz** [comment]
This is becoming ridicolous. Bad bot!

**Comment by batoul-alani** [comment]
up

**Comment by JeffTyfoom** [comment]
up

**Comment by sneurlax** [comment]
Bad bot.  See #1336 (my preference) and #1380.  This is a persistent issue.

**Comment by renancacao** [comment]
ok, bad bot

**Comment by zambetpentru** [comment]
Bad bot

**Comment by zambetpentru** [comment]
Bad bot

**Comment by stan-at-work** [comment]
Add the state tag please...

**Comment by rohinton-collins** [comment]
I fixed this by
```
-    FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image, compressionQuality: 0);
+    FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['png', 'jpg', 'jpeg'], compressionQuality: 0);
```

I already had
```
android:launchMode="singleTop"
```

**Comment by sneurlax** [comment]
Bad bot :)

**Comment by stan-at-work** [comment]
Could someone close and reopen this. The notifications are annoying me.

**Comment by Mandar-100** [comment]
I am still facing these issue can anyone give me a solution for these???.
Thanks inn advance.

**Comment by rohintonc** [comment]
@Mandar-100 https://github.com/miguelpruivo/flutter_file_picker/issues/1404#issuecomment-2229002032

**Comment by rohintonc** [comment]
> I am still facing these issue can anyone give me a solution for these???. Thanks inn advance.

https://github.com/miguelpruivo/flutter_file_picker/issues/1404#issuecomment-2229002032

**Comment by stephane-archer** [comment]
https://github.com/miguelpruivo/flutter_file_picker/issues/1628

**Comment by Henry-Hiles** [comment]
@melWiss would it be possible for you to rebase your branch to have the latest changes with your fixes? Thanks!

**Comment by Henry-Hiles** [comment]
Turns out to be an easy, one line fix, so I made my own fork: https://github.com/henry-hiles/flutteer_file_picker

**Comment by melWiss** [comment]
hey, sorry I just saw the notification and totally forgot about this issue (in our codebase we used our fork directly), is your fork merged to main? @Henry-Hiles 
> @melWiss would it be possible for you to rebase your branch to have the latest changes with your fixes? Thanks!

**Comment by TheCarpetMerchant** [comment]
@miguelpruivo I also, to this day since 2 years ago, have been using my own fork in order to work around this problem.
It is extremely easy to reproduce (use the pickFile function Android 14 to select a non-standard document, like .xyz) and I've had literally hundreds of thousands of users not report an issue. Is there any reason this hasn't been solved ?

**Comment by Henry-Hiles** [comment]
> [@miguelpruivo](https://github.com/miguelpruivo) I also, to this day since 2 years ago, have been using my own fork in order to work around this problem. It is extremely easy to reproduce (use the pickFile function on Android 14 to select a non-standard document, like .xyz) and I've had literally hundreds of thousands of users not report an issue. Is there any reason this hasn't been solved ?

I think it breaks compatability with older android versions.

**Comment by doudar** [comment]
Broken here as well. Trying to pick a .zwo file. It works on older android devices, but not newer devices.

**Comment by Henry-Hiles** [comment]
> Broken here as well. Trying to pick a .zwo file. It works on older android devices, but not newer devices.

You can use my fork: https://github.com/henry-hiles/flutter_file_picker

I think it may break compatability with older android versions though.

**Comment by joma1021** [comment]
any news on this issue?

**Comment by pkd234** [comment]
Its working on older version for me tried `6.2.1`.
