### ISSUE TITLE
[macOS] Hide/Unselect file extension in Save-as dialog

### ISSUE THREAD

**Issue by kaciula** [miguelpruivo/flutter_file_picker#1740]
When saving a file on macOS, the Save-as dialog shows and automatically selects the entire filename with the extension included. This is undesirable because users rename the file name before saving and unknowingly delete the extension at the end.

Some other macOS apps automatically select the filename without the extension in the Save-As dialog so it looks like it's possible. Can you please add a setting to enable this behavior?

**Comment by navaronbracke** [comment]
You probably want to use https://developer.apple.com/documentation/appkit/nssavepanel/isextensionhidden ?
I think if we set that to `false` in https://github.com/miguelpruivo/flutter_file_picker/blob/master/macos/file_picker/Sources/file_picker/FilePickerPlugin.swift#L136-L149 that should fix this bug?

Per the docs:

```
When the value of this property is false, NSSavePanel shows the filename extension in places where you refer to the file by name. The user can override this value by checking the hide extension menu item, which reflects this value. The default value is true.
```

setting this to false still allows the user to show the extension? (using a toggle in the panel)

Feel free to submit a PR to address this.

**Comment by philenius** [comment]
From debugging, I can confirm that setting `dialog.isExtensionHidden = true` hides the file extension. However there are two flaws:

1. Hiding the file extension only works as long as the user has not enabled `Show all filename extensions` in the advanced section of the Finder settings (this took me a while to figure out since `dialog.isExtensionHidden = true` had no effect on my device):
<img width="405" alt="Image" src="https://github.com/user-attachments/assets/5e146900-c3ea-41d8-b894-cf8eaa3115f0" />

2. As you can see in the screen recording, the user can still overwrite the file extension:

https://github.com/user-attachments/assets/5dc74fe2-ffc4-4669-bf14-37901dffe544

Maybe I'm missing something here.

**Comment by kaciula** [comment]
@navaronbracke  I'm seeing the same behavior as @philenius . An alternative would be to somehow select the filename without the extension in the Save-As dialog (but still show the extension as unselected). I'm seeing that several macOS apps do this so it is possible somehow.

**Comment by vicajilau** [comment]
Opened a fix: dialog.isExtensionHidden = true is now set in handleSaveFile, matching what was suggested here. Note this only hides the extension by default, the user can still reveal and edit it via the panel's own toggle, that part is a known limitation of NSSavePanel itself and not fully fixable at the plugin level. See #2147.
